#!/usr/bin/env bash

source "`dirname \"$0\"`/read-env-config"

for i in "$@"
do
case $i in
    -u|--user)
    LOGIN="$2"
    shift # past argument
    shift # past value
    ;;
    -s|--service)
    SERVICE="$2"
    shift # past argument
    shift # past value
    ;;
    --default)
    DEFAULT=YES
    shift # past argument
    shift # past value
    ;;
esac
done

if [[ -z ${LOGIN} ]]; then
  USER=${PROJECT_USER}
else
  USER=${LOGIN}
fi

if [[ -z ${SERVICE} ]]; then
  SERVICE=php
else
  SERVICE=${SERVICE}
fi

cd "`dirname \"$0\"`/.."
docker-compose exec --user ${USER} ${SERVICE} bash